#!/usr/bin/bash

here=pwd
# echo ${here}

# doxyfile="dox/DoxyHtml"
# if [ -f ${doxyfile} ]
# 	then
# 		doxygen ${doxyfile}
# fi

doxyfile="dox/DoxyMan"
if [ -f ${doxyfile} ]
	then
		doxygen ${doxyfile}
fi



doxyfile="dox/DoxyHome"
if [ -f ${doxyfile} ]
	then
		doxygen ${doxyfile}
fi

doxyfile="dox/DoxyRefman"
if [ -f ${doxyfile} ]
	then
		doxygen ${doxyfile}
		cd doc/refman/latex
		make
		cd $here
fi

doxyfile="dox/DoxyUserman"
if [ -f ${doxyfile} ]
	then
		doxygen ${doxyfile}
# 		cd doc/userman/latex
# 		make
# 		cd $here
fi

doxyfile="dox/DoxyLangman"
if [ -f ${doxyfile} ]
	then
		doxygen ${doxyfile}
		cd doc/langman/latex
		make
		cd $here
fi

doxyfile="dox/DoxyStlman"
if [ -f ${doxyfile} ]
	then
		doxygen ${doxyfile}
# 		cd doc/stlman/latex
# 		make
# 		cd $here
fi

# echo ${here}
