#!/usr/bin/env python3

import sys
from SubsetParser       import SubsetParser
from SubsetTransformer  import SubsetTransformer
#from SubsetStatement    import SubsetStatement
#from lark import Lark, Tree, Token, Transformer
#import lark

# read in file
infile      = open(sys.argv[1])
input: str  = infile.read()
infile.close()

# parse file
parser      = SubsetParser()
tree        = parser.parse(input)
#print(tree.pretty())
#print(tree)

# transform tree
STrans      = SubsetTransformer()
x_form_tree = STrans.transform(tree)
result      = []
for child in x_form_tree.children:
    result.append(child)
#print(result)
#control     = '[{Instruction print: [8]}, {Instruction print: [7, 9]}]'
#print(control)
#print('match:', str(result) == control)

# Build IR
#SIRB        = SubsetIRBuilder(result)
#mod         = SIRB.build()
#print(mod)

# Run IR
#SE          = SubsetExecutor(mod)
#SE.run()
##print(SE)
