#!/usr/bin/env python3

import sys
from SubsetParser       import SubsetParser
from SubsetTransformer  import SubsetTransformer
#from SubsetStatement    import SubsetStatement
#from lark import Lark, Tree, Token, Transformer
#import lark

# read in file
infile      = open(sys.argv[1])
input: str  = infile.read()
infile.close()

# parse file
parser      = SubsetParser()
tree        = parser.parse(input)

# transform tree
STrans      = SubsetTransformer()
x_form_tree = STrans.transform(tree)
result      = []
for child in x_form_tree.children:
    result.append(child)
print(result)
#control     = '[{Instruction print: [8]}, {Instruction print: [7, 9]}]'
#print(control)
#print('match:', str(result) == control)

# Interpreter fun!
#I           = Interpreter()
#I.interpret(result)
